name: Continous Integration / Continous Delivery

on: 
  workflow_dispatch

env:
  ARTIFACT_NAME: MAUI.Installer
  PROJECT_PATH: src\MauiWithGitActions\MauiWithGitActions.csproj
  PFX_ASC_FILE: cert.pfx.asc
  PFX_FILE: cert.pfx

jobs:
  Build: 
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Decrypt PFX Certificate file
        run: | 
            echo "${{secrets.WINDOWS_PFX_FILE}}" > ${{env.PFX_ASC_FILE}}
            certutil -decode ${{env.PFX_ASC_FILE}} ${{env.PFX_FILE}}

      - name: Add Cert to Windows Host
        run: certutil -user -q -p ${{secrets.WINDOWS_PFX_PASSWORD}} -importpfx ${{env.PFX_FILE}} NoRoot

      - name: Publish app for release
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release -f:net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{secrets.WINDOWS_PFX_PRINT}}"
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: .\**\AppPackages\**\*.*