name: Continous Integration / Continous Delivery

on: 
  workflow_dispatch

env:
  ARTIFACT_NAME: MAUI.Installer
  PROJECT_PATH: src\MauiWithGitActions\MauiWithGitActions.csproj

jobs:
  Build: 
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Install MAUI Workload
        run: dotnet workload install mau

      - name: Build app for release
        run: dotnet build ${{env.PROJECT_PATH}} -c Release -f:net6.0-windows10.0.19041.0
