name: Continous Integration / Continous Delivery

on: 
  push:
    tags:
      - v*.*

env:
  PROJECT_PATH: src\MauiWithGitActions\MauiWithGitActions.csproj
  PFX_ASC_FILE: cert.pfx.asc
  PFX_FILE: cert.pfx

jobs:
  Build: 
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Build
        run: dotnet build ${{env.PROJECT_PATH}} -c Release  

      - name: Test
        run: dotnet test "src\MauiWithGitActions"  --no-restore --verbosity normal  

      - name: Decrypt PFX Certificate file
        run: | 
            echo "${{secrets.WINDOWS_PFX_FILE}}" > ${{env.PFX_ASC_FILE}}
            certutil -decode ${{env.PFX_ASC_FILE}} ${{env.PFX_FILE}}

      - name: Add Cert to Windows Host
        run: certutil -user -q -p ${{secrets.WINDOWS_PFX_PASSWORD}} -importpfx ${{env.PFX_FILE}} NoRoot

      - name: Publish app for release
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release -f:net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{secrets.WINDOWS_PFX_PRINT}}"
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: .\**\AppPackages\**\MauiWithGitActions*.msix
          allowUpdates: true
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}