name: first

on: push

jobs:
  job1: 
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: echo Current date:$now
      
      
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: date /t
        
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: 
          mydate=`date "+%Y-%m-%d";`
          echo The date is:${mydate}
        
  job4:
    name: Forth Job
    runs-on: macos-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: echo My Forth Current date:$now
